#!usr/bin/php
<?php
$bd = new mysqli("localhost","root","july1696","it202");
if ($db->connect_errno > 0)
{
    echo __FILE__.__LINE__." ERROR: ".$db->connect_error.PHP_EOL;
    exit(-1);
}
echo "We are connected to the DATABASE".PHP_EOL;
$d->close();
?>